// 页面交互：读取预计算数据，绘制价格图、能量日历，并更新回测摘要。
document.addEventListener('DOMContentLoaded', async () => {
  const $ = (selector) => document.querySelector(selector);
  const $$ = (selector) => [...document.querySelectorAll(selector)];
  const money = (value) => Number.isFinite(value) ? `$${value.toLocaleString('en-US', { maximumFractionDigits: value < 10 ? 2 : 0 })}` : '—';
  const price = (value) => Number.isFinite(value) ? `$${value.toLocaleString('en-US', { maximumFractionDigits: value < 1 ? 4 : 0 })}` : '—';
  const pct = (value, digits = 2) => Number.isFinite(value) ? `${value >= 0 ? '+' : ''}${value.toFixed(digits)}%` : '—';
  const weekday = (date) => ['日', '一', '二', '三', '四', '五', '六'][new Date(`${date}T00:00:00Z`).getUTCDay()];
  const status = (row) => row.returnPct > 0 ? '上涨' : row.isMetalWaterDay && row.returnPct < 0 && row.returnPct >= -1 ? '中性偏弱' : row.returnPct < 0 ? '下跌' : '平盘';
  const showToast = (message) => { const toast = $('#toast'); toast.textContent = message; toast.classList.add('show'); window.clearTimeout(showToast.timer); showToast.timer = window.setTimeout(() => toast.classList.remove('show'), 1800); };
  if (window.lucide) window.lucide.createIcons();
  const response = await fetch('data/analysis.json');
  if (!response.ok) throw new Error(`analysis.json: ${response.status}`);
  const data = await response.json();
  const latest = data.latest; const baseline = data.stats.baseline; const metal = data.stats.metalWater; const strong = data.stats.strongMetalWater;

  $('#data-status').textContent = `数据截至 ${latest.date}`; $('#hero-date').textContent = latest.date; $('#hero-price').textContent = money(latest.price); $('#hero-change').textContent = pct(latest.returnPct); $('#hero-change').classList.toggle('positive', latest.returnPct >= 0); $('#hero-lunar').textContent = latest.lunar; $('#hero-pillar').textContent = `${latest.dayPillar} / ${latest.monthPillar}`; $('#hero-energy').textContent = latest.energyLabel; $('#metric-samples').textContent = metal.samples.toLocaleString(); $('#metric-accuracy').textContent = `${metal.accuracy.toFixed(2)}%`; $('#metric-baseline').textContent = `${baseline.accuracy.toFixed(2)}%`; $('#metric-accuracy-note').textContent = `较基准 ${pct(metal.accuracy - baseline.accuracy, 2)}`; $('#metric-month').textContent = latest.monthPillar; $('#metric-month-note').textContent = latest.monthPillar === '丁酉' ? '丁酉月进行中' : '按节气月柱'; $('#footer-date').textContent = latest.date;

  function setupCanvas(canvas) { const rect = canvas.getBoundingClientRect(); const ratio = Math.max(window.devicePixelRatio || 1, 1); canvas.width = Math.max(Math.round(rect.width * ratio), 300); canvas.height = Math.max(Math.round(rect.height * ratio), 150); const ctx = canvas.getContext('2d'); ctx.setTransform(ratio, 0, 0, ratio, 0, 0); return { ctx, width: rect.width, height: rect.height }; }
  function drawChart(canvas, rows, dark = false) {
    const { ctx, width, height } = setupCanvas(canvas); ctx.clearRect(0, 0, width, height); if (!rows.length) return; const values = rows.map((row) => row.price); const min = Math.min(...values); const max = Math.max(...values); const span = max - min || 1; const pad = { top: 14, right: 8, bottom: 17, left: 8 }; const x = (index) => pad.left + index / Math.max(rows.length - 1, 1) * (width - pad.left - pad.right); const y = (value) => pad.top + (max - value) / span * (height - pad.top - pad.bottom);
    ctx.strokeStyle = dark ? 'rgba(177,211,198,.14)' : '#e7e8e2'; ctx.lineWidth = 1; for (let step = 1; step < 4; step += 1) { const lineY = pad.top + (height - pad.top - pad.bottom) * step / 4; ctx.beginPath(); ctx.moveTo(pad.left, lineY); ctx.lineTo(width - pad.right, lineY); ctx.stroke(); }
    ctx.beginPath(); rows.forEach((row, index) => { const px = x(index); const py = y(row.price); index ? ctx.lineTo(px, py) : ctx.moveTo(px, py); }); ctx.strokeStyle = dark ? '#9fceb9' : '#1e5f58'; ctx.lineWidth = 2; ctx.stroke(); rows.forEach((row, index) => { if (!row.isMetalWaterDay && !row.isEarthDay) return; ctx.beginPath(); ctx.arc(x(index), y(row.price), 2.5, 0, Math.PI * 2); ctx.fillStyle = row.isEarthDay ? '#c43d45' : '#e67b43'; ctx.fill(); });
  }
  const renderHeroChart = () => drawChart($('#hero-chart'), data.recent.slice(-90), true); renderHeroChart();
  const chartWindowLabel = { 90: '最近 90 天', 365: '最近 1 年', all: '全部历史' };
  let chartRows = data.daily.slice(-90); let chartStart = 0; let chartEnd = chartRows.length;
  function renderPriceChart(windowKey = '90') { chartRows = windowKey === 'all' ? data.daily : data.daily.slice(-Number(windowKey)); chartStart = 0; chartEnd = chartRows.length; drawChart($('#price-chart'), chartRows, false); $('#chart-range-label').textContent = chartWindowLabel[windowKey]; $('#chart-note').textContent = `${chartRows[0].date} → ${chartRows.at(-1).date} · 滚轮缩放 / 拖拽平移 · 红点为土属性日`; }
  renderPriceChart(); $$('[data-window]').forEach((button) => button.addEventListener('click', () => { $$('[data-window]').forEach((item) => item.classList.remove('active')); button.classList.add('active'); renderPriceChart(button.dataset.window); })); window.addEventListener('resize', () => { renderHeroChart(); renderPriceChart(document.querySelector('[data-window].active')?.dataset.window || '90'); });

  // 价格图支持滚轮缩放、拖拽平移和双击复位，保持静态页面也有交易图表的基本观察能力。
  const priceCanvas = $('#price-chart'); let dragX = null;
  priceCanvas.addEventListener('wheel', (event) => { event.preventDefault(); const span = chartEnd - chartStart; const next = Math.max(20, Math.min(chartRows.length, Math.round(span * (event.deltaY > 0 ? 1.2 : .8)))); const center = chartStart + span / 2; chartStart = Math.max(0, Math.round(center - next / 2)); chartEnd = Math.min(chartRows.length, chartStart + next); chartStart = Math.max(0, chartEnd - next); drawChart(priceCanvas, chartRows.slice(chartStart, chartEnd)); }, { passive: false });
  priceCanvas.addEventListener('pointerdown', (event) => { dragX = event.clientX; priceCanvas.setPointerCapture(event.pointerId); });
  priceCanvas.addEventListener('pointermove', (event) => { if (dragX === null) return; const delta = Math.round((dragX - event.clientX) / Math.max(priceCanvas.clientWidth, 1) * (chartEnd - chartStart)); if (!delta) return; const span = chartEnd - chartStart; chartStart = Math.max(0, Math.min(chartRows.length - span, chartStart + delta)); chartEnd = chartStart + span; dragX = event.clientX; drawChart(priceCanvas, chartRows.slice(chartStart, chartEnd)); });
  priceCanvas.addEventListener('pointerup', () => { dragX = null; }); priceCanvas.addEventListener('dblclick', () => { chartStart = 0; chartEnd = chartRows.length; drawChart(priceCanvas, chartRows); });

  $('#latest-table').innerHTML = data.daily.slice(-14).reverse().map((row) => `<tr><td>${row.date}</td><td>${price(row.highPrice)}</td><td>${price(row.lowPrice)}</td><td>${price(row.price)}</td><td class="${row.isEarthDay ? 'earth-text' : ''}"><i class="pillar-dot ${row.isEarthDay ? 'earth' : row.metalWaterScore === 2 ? 'metal' : row.metalWaterScore === 1 ? 'single' : ''}"></i>${row.dayPillar}</td></tr>`).join('');
  const monthKeys = [...new Set(data.daily.map((row) => row.date.slice(0, 7)))].reverse(); const monthSelect = $('#month-select'); monthSelect.innerHTML = monthKeys.slice(0, 18).map((month) => `<option value="${month}">${month.replace('-', ' 年 ')} 月</option>`).join('');
  function renderCalendar(month) { const first = new Date(`${month}-01T00:00:00Z`); const dayOfWeek = (first.getUTCDay() + 6) % 7; const rows = data.daily.filter((row) => row.date.startsWith(month)); const map = new Map(rows.map((row) => [row.date, row])); const daysInMonth = new Date(Date.UTC(first.getUTCFullYear(), first.getUTCMonth() + 1, 0)).getUTCDate(); const cells = Array.from({ length: dayOfWeek }, () => '<div class="day-cell empty"></div>'); for (let day = 1; day <= daysInMonth; day += 1) { const date = `${month}-${String(day).padStart(2, '0')}`; const row = map.get(date); if (!row) { cells.push('<div class="day-cell empty"></div>'); continue; } const energy = row.isEarthDay ? 'earth' : row.metalWaterScore === 2 ? 'metal' : row.metalWaterScore === 1 ? 'single' : ''; const lunarShort = row.lunar.split('年').at(-1)?.slice(0, 5) || row.lunar; const eventText = row.highlightEvents.join(' · '); cells.push(`<div class="day-cell ${energy} ${row.returnPct >= 0 ? 'positive' : 'negative'}">${row.isPinnedLowPoint ? '<span class="pin-mark">📌</span>' : ''}<div class="day-top"><span class="solar">${day} ${weekday(date)}</span><span class="return">${pct(row.returnPct, 1)}</span></div><div class="lunar">${lunarShort}</div><div class="pillar">${row.dayPillar} · ${row.dayElement}</div><div class="price-mini">收 ${price(row.price)}</div>${eventText ? `<span class="festival-mark">${eventText}</span>` : ''}<i class="energy-mark"></i></div>`); } $('#calendar-grid').innerHTML = cells.join(''); const up = rows.filter((row) => row.returnPct > 0).length; const energyRows = rows.filter((row) => row.isMetalWaterDay); const energyUp = energyRows.filter((row) => row.returnPct > 0).length; const earthRows = rows.filter((row) => row.isEarthDay); $('#month-stat').textContent = `${rows.length} 天 · 金水日 ${energyRows.length} 天 · 土属性日 ${earthRows.length} 天 · 金水上涨 ${energyUp}/${energyRows.length} · 全月上涨 ${up}/${rows.length}`; $('#calendar-detail-title').textContent = `${month} · 历史具体价格`; $('#calendar-detail-table').innerHTML = rows.map((row) => `<tr><td>${row.date.slice(5)} 周${weekday(row.date)}</td><td>${row.lunar.split('年').at(-1)}</td><td class="${row.isEarthDay ? 'earth-text' : ''}">${row.dayPillar}</td><td class="${row.isEarthDay ? 'earth-text' : ''}">${row.dayElement}</td><td class="${row.metalWaterElements.length ? 'positive-text' : ''}">${row.metalWaterLabel}</td><td>${price(row.highPrice)}</td><td>${price(row.lowPrice)}</td><td>${price(row.price)}</td><td class="${row.isPinnedLowPoint ? 'pin-text' : row.returnPct >= 0 ? 'positive-text' : 'negative-text'}">${row.isPinnedLowPoint ? `📌 ${row.lowPointNote}` : status(row)}</td><td>${row.highlightEvents.join(' · ') || '—'}</td></tr>`).join(''); }
  renderCalendar(monthKeys[0]); monthSelect.addEventListener('change', () => renderCalendar(monthSelect.value));

  const setBar = (id, value) => { $(id).style.width = `${Math.min(value, 100)}%`; }; $('#bar-baseline-value').textContent = `${baseline.accuracy.toFixed(2)}%`; $('#bar-metal-value').textContent = `${metal.accuracy.toFixed(2)}%`; $('#bar-strong-value').textContent = `${strong.accuracy.toFixed(2)}%`; setBar('#bar-baseline', baseline.accuracy); setBar('#bar-metal', metal.accuracy); setBar('#bar-strong', strong.accuracy); $('#accuracy-delta').textContent = pct(metal.directionalAccuracy - baseline.directionalAccuracy); $('#avg-metal').textContent = pct(metal.avgReturn, 4); $('#neutral-metal').textContent = `${metal.neutralWeakDays.toLocaleString()} 天`; $('#directional-metal').textContent = `${metal.directionalAccuracy.toFixed(2)}%`; $('#strong-samples').textContent = strong.samples.toLocaleString(); $('#evidence-title').textContent = metal.accuracy > baseline.accuracy ? '金水日上涨率略高，但小跌先归中性偏弱' : '金水日没有高于全样本基准'; $('#evidence-copy').textContent = `金水日上涨率 ${metal.accuracy.toFixed(2)}%，方向性正确率 ${metal.directionalAccuracy.toFixed(2)}%；跌幅在 1% 内的 ${metal.neutralWeakDays.toLocaleString()} 天单列为中性偏弱。`;

  const completed = data.dingYou.historical.filter((month) => month.end < latest.date); const finishedMoves = completed.map((month) => month.returnPct).filter(Number.isFinite); const completedUp = finishedMoves.filter((value) => value > 0).length; $('#dingyou-up-rate').textContent = `${finishedMoves.length ? (completedUp / finishedMoves.length * 100).toFixed(1) : '—'}%`; $('#dingyou-median').textContent = finishedMoves.length ? pct(finishedMoves.slice().sort((a, b) => a - b)[Math.floor(finishedMoves.length / 2)]) : '—'; $('#dingyou-next').textContent = data.dingYou.future.length; $('#dingyou-table').innerHTML = data.dingYou.months.map((month) => { const statusClass = month.status === '上涨' ? 'up' : month.status === '下跌' ? 'down' : 'future'; const move = month.returnPct === null ? '—' : pct(month.returnPct); return `<tr><td>${month.year}</td><td>${month.start} → ${month.end}</td><td>${month.days} 天</td><td class="${month.returnPct >= 0 ? 'positive-text' : 'negative-text'}">${move}</td><td><span class="status-tag ${statusClass}">${month.status}${month.year === 2026 ? ' · 未完结' : ''}</span></td></tr>`; }).join(''); $('#halving-list').innerHTML = data.halvingWindows.map((item) => { const years = item.window.match(/\d{4}/g)?.map(Number) || []; const mapped = years.length > 1 ? data.dingYou.future.filter((month) => month.year >= years[0] && month.year < years[1]) : []; const label = mapped.length ? `丁酉月 ${mapped.map((month) => month.year).join(' / ')}` : '无丁酉月'; return `<div class="halving-item"><i></i><div><strong>${item.label}</strong><span>${item.anchor} · ${item.window}</span></div><em>${label}</em></div>`; }).join('');
  // 展示当前数据之后至 2042 年的全部节气月柱与五行属性，不虚构未来价格。
  const futureSolarTerms = data.futureSolarTerms || []; $('#solar-term-forecast-count').textContent = `${futureSolarTerms.length} 个节气`; $('#solar-term-forecast-table').innerHTML = futureSolarTerms.map((term) => `<tr><td>${term.date} 周${weekday(term.date)}</td><td>${term.time}</td><td>${term.solarTerm}</td><td>${term.monthPillar}</td><td>${term.monthGan} · ${term.monthGanElement}</td><td>${term.monthZhi} · ${term.monthBranchElement}</td><td>${term.elementLabel}</td></tr>`).join('');

  const sections = $$('[data-section]'); const navLinks = $$('[data-nav]'); const observer = new IntersectionObserver((entries) => { const visible = entries.filter((entry) => entry.isIntersecting).sort((a, b) => b.intersectionRatio - a.intersectionRatio)[0]; if (!visible) return; navLinks.forEach((link) => link.classList.toggle('active', link.dataset.nav === visible.target.dataset.section)); }, { rootMargin: '-18% 0px -67% 0px', threshold: [0,.2,.5] }); sections.forEach((section) => observer.observe(section));
  const themeToggle = $('#theme-toggle'); if (localStorage.getItem('btc-energy-theme') === 'dark') document.body.classList.add('dark'); themeToggle.addEventListener('click', () => { document.body.classList.toggle('dark'); localStorage.setItem('btc-energy-theme', document.body.classList.contains('dark') ? 'dark' : 'light'); renderHeroChart(); renderPriceChart(document.querySelector('[data-window].active')?.dataset.window || '90'); showToast(document.body.classList.contains('dark') ? '已切换深色模式' : '已切换浅色模式'); });
});
